//
//  Constants.swift
//  SuperCoolYelp
//
//  Created by Eden on 9/22/17.
//  Copyright © 2017 Timothy Lee. All rights reserved.
//

import Foundation

struct Constants {
    
//    var categories = [Filter(name:  "Afghan", value: false, parentGroup: 4, identifier: 0, code: nil),
//                      Filter(name:  "African", value: false, parentGroup: 4, identifier: 1),
//                      Filter(name:  "American, New", value: false, parentGroup: 4, identifier: 2),
//                      Filter(name:  "American, Traditional", value: false, parentGroup: 4, identifier: 3),
//                      Filter(name:  "Arabian", value: false, parentGroup: 4, identifier: 4),
//                      Filter(name:  "Argentine", value: false, parentGroup: 4, identifier: 5),
//                      Filter(name:  "Armenian", value: false, parentGroup: 4, identifier: 6),
//                      Filter(name:  "Asian Fusion", value: false, parentGroup: 4, identifier: 7),
//                      Filter(name:  "Asturian", value: false, parentGroup: 4, identifier: 8),
//                      Filter(name:  "Australian", value: false, parentGroup: 4, identifier: 9),
//                      Filter(name:  "Austrian", value: false, parentGroup: 4, identifier: 10, code: nil),
//                      Filter(name:  "Baguettes", value: false, parentGroup: 4, identifier: 11),
//                      Filter(name:  "Bangladeshi", value: false, parentGroup: 4, identifier: 12),
//                      Filter(name:  "Barbeque", value: false, parentGroup: 4, identifier: 13),
//                      Filter(name:  "Basque", value: false, parentGroup: 4, identifier: 14),
//                      Filter(name:  "Bavarian", value: false, parentGroup: 4, identifier: 15),
//                      Filter(name:  "Beer Garden", value: false, parentGroup: 4, identifier: 16)]
    //                        Filter(name:  "Beer Hall", value: false, parentGroup: 4, identifier: 0, code: nil),
    //                        Filter(name:  "Beisl", value: false, parentGroup: 4, identifier: 0, code: nil),
    //                        Filter(name:  "Belgian", value: false, parentGroup: 4, identifier: 0, code: nil),
    //                        Filter(name:  "Bistros", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Black Sea", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Brasseries", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Brazilian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Breakfast & Brunch", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "British", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Buffets", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Bulgarian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Burgers", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Burmese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cafes", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cafeteria", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cajun/Creole", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cambodian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Canadian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Canteen", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Caribbean", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Catalan", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Chech", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cheesesteaks", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Chicken Shop", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Chicken Wings", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Chilean", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Chinese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Comfort Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Corsican", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Creperies", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cuban", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Curry Sausage", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Cypriot", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Czech", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Czech/Slovakian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Danish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Delis", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Diners", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Dumplings", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Eastern European", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Ethiopian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Fast Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Filipino", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Fish & Chips", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Fondue", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Food Court", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Food Stands", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "French", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "French Southwest", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Galician", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Gastropubs", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Georgian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "German", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Giblets", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Gluten-Free", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Greek", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Halal", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Hawaiian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Heuriger", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Himalayan/Nepalese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Hong Kong Style Cafe", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Hot Dogs", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Hot Pot", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Hungarian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Iberian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Indian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Indonesian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "International", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Irish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Island Pub", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Israeli", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Italian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Japanese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Jewish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Kebab", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Korean", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Kosher", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Kurdish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Laos", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Laotian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Latin American", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Live/Raw Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Lyonnais", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Malaysian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Meatballs", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Mediterranean", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Mexican", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Middle Eastern", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Milk Bars", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Modern Australian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Modern European", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Mongolian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Moroccan", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "New Zealand", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Night Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Norcinerie", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Open Sandwiches", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Oriental", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Pakistani", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Parent Cafes", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Parma", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Persian/Iranian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Peruvian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Pita", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Pizza", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Polish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Portuguese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Potatoes", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Poutineries", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Pub Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Rice", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Romanian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Rotisserie Chicken", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Rumanian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Russian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Salad", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Sandwiches", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Scandinavian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Scottish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Seafood", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Serbo Croatian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Signature Cuisine", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Singaporean", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Slovakian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Soul Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Soup", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Southern", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Spanish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Steakhouses", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Sushi Bars", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Swabian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Swedish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Swiss Food", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Tabernas", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Taiwanese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Tapas Bars", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Tapas/Small Plates", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Tex-Mex", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Thai", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Traditional Norwegian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Traditional Swedish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Trattorie", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Turkish", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Ukrainian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Uzbek", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Vegan", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Vegetarian", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Venison", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Vietnamese", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Wok", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Wraps", value: false, parentGroup: 4, identifier: 0),
    //                        Filter(name:  "Yugoslav", value: false, parentGroup: 4, identifier: 0)]

    
//    static let categories = ["Afghan": false,
//                             "African": false,
//                             "American, New": false,
//                             "American, Traditional": false,
//                             "Arabian": false,
//                             "Argentine": false,
//                             "Armenian": false,
//                             "Asian Fusion": false,
//                             "Asturian": false,
//                             "Australian": false,
//                             "Austrian": false,
//                             "Baguettes": false,
//                             "Bangladeshi": false,
//                             "Barbeque": false,
//                             "Basque": false,
//                             "Bavarian": false,
//                             "Beer Garden": false,
//                             "Beer Hall": false,
//                             "Beisl": false,
//                             "Belgian": false,
//                             "Bistros": false,
//                             "Black Sea": false,
//                             "Brasseries": false,
//                             "Brazilian": false,
//                             "Breakfast & Brunch": false,
//                             "British": false,
//                             "Buffets": false,
//                             "Bulgarian": false,
//                             "Burgers": false,
//                             "Burmese": false,
//                             "Cafes": false,
//                             "Cafeteria": false,
//                             "Cajun/Creole": false,
//                             "Cambodian": false,
//                             "Canadian": false,
//                             "Canteen": false,
//                             "Caribbean": false,
//                             "Catalan": false,
//                             "Chech": false,
//                             "Cheesesteaks": false,
//                             "Chicken Shop": false,
//                             "Chicken Wings": false,
//                             "Chilean": false,
//                             "Chinese": false,
//                             "Comfort Food": false,
//                             "Corsican": false,
//                             "Creperies": false,
//                             "Cuban": false,
//                             "Curry Sausage": false,
//                             "Cypriot": false,
//                             "Czech": false,
//                             "Czech/Slovakian": false,
//                             "Danish": false,
//                             "Delis": false,
//                             "Diners": false,
//                             "Dumplings": false,
//                             "Eastern European": false,
//                             "Ethiopian": false,
//                             "Fast Food": false,
//                             "Filipino": false,
//                             "Fish & Chips": false,
//                             "Fondue": false,
//                             "Food Court": false,
//                             "Food Stands": false,
//                             "French": false,
//                             "French Southwest": false,
//                             "Galician": false,
//                             "Gastropubs": false,
//                             "Georgian": false,
//                             "German": false,
//                             "Giblets": false,
//                             "Gluten-Free": false,
//                             "Greek": false,
//                             "Halal": false,
//                             "Hawaiian": false,
//                             "Heuriger": false,
//                             "Himalayan/Nepalese": false,
//                             "Hong Kong Style Cafe": false,
//                             "Hot Dogs": false,
//                             "Hot Pot": false,
//                             "Hungarian": false,
//                             "Iberian": false,
//                             "Indian": false,
//                             "Indonesian": false,
//                             "International": false,
//                             "Irish": false,
//                             "Island Pub": false,
//                             "Israeli": false,
//                             "Italian": false,
//                             "Japanese": false,
//                             "Jewish": false,
//                             "Kebab": false,
//                             "Korean": false,
//                             "Kosher": false,
//                             "Kurdish": false,
//                             "Laos": false,
//                             "Laotian": false,
//                             "Latin American": false,
//                             "Live/Raw Food": false,
//                             "Lyonnais": false,
//                             "Malaysian": false,
//                             "Meatballs": false,
//                             "Mediterranean": false,
//                             "Mexican": false,
//                             "Middle Eastern": false,
//                             "Milk Bars": false,
//                             "Modern Australian": false,
//                             "Modern European": false,
//                             "Mongolian": false,
//                             "Moroccan": false,
//                             "New Zealand": false,
//                             "Night Food": false,
//                             "Norcinerie": false,
//                             "Open Sandwiches": false,
//                             "Oriental": false,
//                             "Pakistani": false,
//                             "Parent Cafes": false,
//                             "Parma": false,
//                             "Persian/Iranian": false,
//                             "Peruvian": false,
//                             "Pita": false,
//                             "Pizza": false,
//                             "Polish": false,
//                             "Portuguese": false,
//                             "Potatoes": false,
//                             "Poutineries": false,
//                             "Pub Food": false,
//                             "Rice": false,
//                             "Romanian": false,
//                             "Rotisserie Chicken": false,
//                             "Rumanian": false,
//                             "Russian": false,
//                             "Salad": false,
//                             "Sandwiches": false,
//                             "Scandinavian": false,
//                             "Scottish": false,
//                             "Seafood": false,
//                             "Serbo Croatian": false,
//                             "Signature Cuisine": false,
//                             "Singaporean": false,
//                             "Slovakian": false,
//                             "Soul Food": false,
//                             "Soup": false,
//                             "Southern": false,
//                             "Spanish": false,
//                             "Steakhouses": false,
//                             "Sushi Bars": false,
//                             "Swabian": false,
//                             "Swedish": false,
//                             "Swiss Food": false,
//                             "Tabernas": false,
//                             "Taiwanese": false,
//                             "Tapas Bars": false,
//                             "Tapas/Small Plates": false,
//                             "Tex-Mex": false,
//                             "Thai": false,
//                             "Traditional Norwegian": false,
//                             "Traditional Swedish": false,
//                             "Trattorie": false,
//                             "Turkish": false,
//                             "Ukrainian": false,
//                             "Uzbek": false,
//                             "Vegan": false,
//                             "Vegetarian": false,
//                             "Venison": false,
//                             "Vietnamese": false,
//                             "Wok": false,
//                             "Wraps": false,
//                             "Yugoslav": false]
}

